spring:
  application:
    name: api-gateway
  cloud.config.import-check.enabled: false


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info



poc:
  address:
    customer: 47.129.150.214:8080
    insurance: ec2-13-228-75-181.ap-southeast-1.compute.amazonaws.com:8000
    vet: 52.221.233.113:8080
    billing: 13.212.101.100:8800


server:
  error:
    include-message: always

logging:
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
